#!/bin/bash
# Quick Start - Sistema TODO

echo "🚀 SISTEMA TODO - INICIO RÁPIDO"
echo "================================="
echo ""
echo "📋 Opciones disponibles:"
echo ""
echo "1️⃣  MODO DEMO (localStorage - SIN BACKEND)"
echo "   $ cd frontend && npm install && npm start"
echo "   Credenciales: prueba@example.com / prueba12345678"
echo ""
echo "2️⃣  MODO REAL (con Backend)"
echo "   $ cd backend && python manage.py runserver"
echo "   $ cd frontend && npm start"
echo "   Luego edita frontend/.env.local:"
echo "   REACT_APP_USE_MOCK=false"
echo "   REACT_APP_API_URL=http://localhost:8000/api"
echo ""
echo "3️⃣  DESPLIEGUE PRODUCCIÓN (Demo sin backend)"
echo "   $ cd frontend && REACT_APP_USE_MOCK=true npm run build"
echo "   Sube /build a Vercel o Netlify"
echo ""
echo "📖 Documentación:"
echo "   - MOCK_API_GUIDE.md (Detalles técnicos)"
echo "   - frontend/README_SETUP.md (Quick start)"
echo ""
echo "✅ Sistema listo. ¡Comienza con la Opción 1!"
