# Generated by Django 5.2.8 on 2025-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='repeticion',
            field=models.CharField(choices=[('ninguna', 'No repetir'), ('semanal', 'Cada semana'), ('mensual', 'Cada mes'), ('anual', 'Cada año')], default='ninguna', max_length=20),
        ),
    ]
