# Generated by Django 5.2.8 on 2025-11-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_repeticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='es_tarea_padre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin_repeticion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='repeticion',
            field=models.CharField(choices=[('ninguna', 'No repetir'), ('diaria', 'Cada día'), ('semanal', 'Cada semana'), ('mensual', 'Cada mes')], default='ninguna', max_length=20),
        ),
        migrations.CreateModel(
            name='InstanciaTarea',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instancia', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tarea_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='tareas.tarea')),
            ],
            options={
                'db_table': 'instancias_tareas',
                'ordering': ['fecha_instancia'],
                'unique_together': {('tarea_padre', 'fecha_instancia')},
            },
        ),
    ]
