# Generated by Django 5.2.8 on 2025-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_activa_tarea_es_tarea_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_recurrencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='intervalo_repeticion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='repeticion',
            field=models.CharField(choices=[('ninguna', 'No repetir'), ('diaria', 'Cada día'), ('semanal', 'Cada semana'), ('mensual', 'Cada mes'), ('personalizada', 'Personalizada')], default='ninguna', max_length=20),
        ),
    ]
