# Generated by Django 5.2.8 on 2025-11-19 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_es_recurrente_tarea_fecha_inicio_recurrencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='es_recurrente',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='es_tarea_padre',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_inicio_recurrencia',
        ),
        migrations.CreateModel(
            name='TareaCompletada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('completada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias_completadas', to='tareas.tarea')),
            ],
            options={
                'db_table': 'tareas_completadas',
                'ordering': ['-completada_en'],
                'unique_together': {('tarea', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='TareaEnProceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias_en_proceso', to='tareas.tarea')),
            ],
            options={
                'db_table': 'tareas_en_proceso',
                'ordering': ['-iniciada_en'],
                'unique_together': {('tarea', 'fecha')},
            },
        ),
        migrations.DeleteModel(
            name='InstanciaTarea',
        ),
    ]
